addons:
  apt:
    packages:
    - nodejs
language: python
sudo: false
dist: xenial
python:
  - "2.7"
env:
  - TOXENV=django18
  - TOXENV=django111
matrix:
  include:
    - python: 2.7
      env: TOXENV=quality
    - python: 2.7
      env: TOXENV=js
before_install:
  - "pip install pip==19.0.3"
  - sudo rm -f /etc/boto.cfg
cache:
    directories:
        - $HOME/.cache/pip
install:
  - "pip install tox"
script:
  - tox
branches:
    only:
      - master
after_success:
  coveralls
